### ISSUE TITLE
Video Modal Autoplay 

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#258]
Hi Sam,

We need to make the video autoplay when the video is opened within the modal window.

Also we need to make it stop playing when the modal window is closed.

Can you sort this out?

I have added ?autoplay to the URL but it seems to have some issues. Can you look into it?

Chris

**Comment by samvthom16** [comment]
@designbychris The video is actually auto playing when you added the autoplay to the URL but you can't see it because its inside the modal that's hidden. So what I have done is to add autoplay to the URL dynamically only when the video modal actually opens. Keeping that in mind, you don't have to add autoplay to your urls. 

Also I noticed that there are some css styling based on the ID: `#squarespaceModalVideoClean`. Could you change them to use the class `.video-modal`. Since these are being created from the page builder widgets, I am supposed to create the id dynamically. Once you update the styles, can I work on that.

**Comment by samvthom16** [comment]
@designbychris Please test this out for me on staging. If it works then lets close the issue.

**Comment by samvthom16** [comment]
https://github.com/akvo/Akvo-Theme/issues/235

**Comment by designbychris** [comment]
@samvthom16 I've changed the CSS to not use the id. So you can now change that to how you need. i'm using the class of the main modal container for the style amends: 

.so-widget-akvo-video-modal

So this should all be good now :) autoplay is working fine now too :) thanks
