### ISSUE TITLE
Check issue with Gravity Forms

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#295]
Hi @samvthom16,

can you have a look at the Gravity Forms on this page:

https://staging3.akvo.org/get-in-touch-2/

It seems to have lost ALL styling, and i'm not sure why, its a duplicate of the form being used on the region pages. But its just not working at all.

Can you check whats going on?

**Comment by samvthom16** [comment]
@designbychris your styling is applied on this selector `.so-widget-sow-editor h3.widget-title`. So the styles are assuming that you will use a shortcode like this one `[gravityform id=22 title=false description=false ajax=true]`. But on the GET IN TOUCH page, you are using a widget instead of the shortcode.

**Comment by designbychris** [comment]
Hi Sam,

On that page, I have both the shortcode and the widget running, but its just not happy.

Any ideas why?

Chris

**Comment by samvthom16** [comment]
@designbychris removed the widget version and it seems to be working now. Form conflicts I guess because of the duplicates.

**Comment by designbychris** [comment]
Great :) thanks
