### ISSUE TITLE
WIDGET for rotating sentence

### ISSUE THREAD

**Issue by designbychris** [akvo/Akvo-Theme#297]
Hi @samvthom16, Laura has requested that we build a Rotating Sentence widget/function for the builder.

I have added 2 files, one is the .php within the /lib folder as normal, and I have added the CSS file to the CSS folder to be added into the rest of the CSS/SCSS as you've changed how that works, and chris.css no longer is being used I believe.

It should look like this: https://codepen.io/amritleone/pen/qERPmW (see the 3rd one down which fades in and out for each item).

I hope this all makes sense.

**Comment by samuelpyramidions** [comment]
@designbychris chris.css will always work. I have refactored and moved the css from there to SCSS. So if you want to add anything in terms of css, use chris,css.

**Comment by samuelpyramidions** [comment]
@designbychris I checked the code locally and the problem is that the fadein effect only works if the items are 5 in number. Any change in the total items messes up with the animation? Any idea how you could make it more dynamic?

**Comment by samvthom16** [comment]
@designbychris chris.css will always work. I have refactored and moved the old css from there to SCSS. So if you want to add anything in terms of css, use chris,css.

I checked the code locally and the problem is that the fadein effect only works if the items are 5 in number. Any change in the total items messes up with the animation? Any idea how you could make it more dynamic?

I have anyways pushed the code for what I have built so far.

**Comment by designbychris** [comment]
Seems to work fine with less than 5 items.. I think that will be fine. I doubt very highly that there will be any call for more than 5. I will take a look at the code again, but I think thats ok at the moment :) I will let Laura know that there is a limit of 5 items in total :)

**Comment by samvthom16** [comment]
@designbychris can we close this then?

**Comment by designbychris** [comment]
Yes :)
