### ISSUE TITLE
Progress bar is green in color 

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#41]

**Comment by samvthom16** [comment]
@designbychris I have been able to figure this one. Can we recreate this one?

**Comment by designbychris** [comment]
so is this needing to be rebuilt @samvthom16 or did you find the problem?

**Comment by samvthom16** [comment]
@designbychris I couldn't figure

**Comment by designbychris** [comment]
ok.. lets leave it for the timebeing.. I will revisit this when we're done with all the more important things :)

**Comment by samvthom16** [comment]
@designbychris what is the plan for this?

**Comment by designbychris** [comment]
Hi Sam,
I think that the plan is to rebuild this when everything else is done :) I have it in my workflow for when we have all the other issues finished. As it might just be as simple as making a new one :)
Chris

**Comment by designbychris** [comment]
Seems to be fixed :)

**Comment by samvthom16** [comment]
@designbychris it would be nice to document how the issue was fixed for future references.

**Comment by designbychris** [comment]
Annoyingly it was just adding a few lines of CSS (as it was a webkit issue), the issue was fixed with the following CSS:

/* PROGRESS BAR FIXES */
progress .progress-bar, .progress-bar, span.progress-bar {color:#03ad8c !important;background-color:#03ad8c !important;background:#03ad8c !important;}

progress::-webkit-progress-bar {
  background-color: transparent;
}

progress::-webkit-progress-value {
  background-color: #03ad8c !important;
}

progress::-moz-progress-bar {
  background-color: #03ad8c !important;
}

I added this code to chris.css and it fixed the problem globally :)
