### ISSUE TITLE
Annual Reports

### ISSUE THREAD

**Issue by samvthom16** [akvo/Akvo-Theme#58]
Linda: It would be good if the 2014 annual report could stay looking as it does. Is that possible?
https://akvo.org/about-us/organisations/annual-report-2014/

**Comment by Lindaleunissen** [comment]
Thanks for this Sam. To elaborate on this: in other years we've done a printed booklet, which is downloadable as a pdf, so there is no problem there. In 2014 the only annual report we did was this online one. 

If possible we'd like to keep this page looking as it does now, so that it has the style and look we used in 2014. I'm open however to the possibility of using an alternative way of retaining the look and feel (thinking pdf or something like that), though preferably we would keep the moving gif and carousel working.
